version: "3.8"

services:
  backend:
    image: khmwe/dino-backend:latest
    platform: linux/amd64
    container_name: springboot-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/dino
    depends_on:
      - mongodb

  frontend:
    image: khmwe/dino-frontend:latest
    platform: linux/amd64
    container_name: dino-frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  mongodb:
    image: mongo:4.4
    platform: linux/amd64
    container_name: dino-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
